development:
  clients:
    default:
      database: mysms_development
      hosts:
        - localhost:27017
      options:
        server_selection_timeout: 5
  options:
    log_level: :debug

test:
  clients:
    default:
      database: mysms_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1

production:
  clients:
    default:
      uri: <%= ENV["MONGODB_URI"] %>
      options:
        server_selection_timeout: 5
        max_pool_size: 10
